INSERT INTO ESTADO_DE_CONSERVACAO (CODIGO, NOME_ESTADO) VALUES (0, "BOM"); 
INSERT INTO ESTADO_DE_CONSERVACAO (CODIGO, NOME_ESTADO) VALUES (1, "REGULAR"); 
INSERT INTO ESTADO_DE_CONSERVACAO (CODIGO, NOME_ESTADO) VALUES (2, "RUIM"); 
INSERT INTO ESTADO_DE_CONSERVACAO (CODIGO, NOME_ESTADO) VALUES (3, "OTIMO"); 
INSERT INTO ESTADO_DE_CONSERVACAO (CODIGO, NOME_ESTADO) VALUES (4, "PESSIMO"); 

